routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::group(['middleware' => ['can:admin'] ], function () {
        Route::resource('/user', 'UserController', ['as' => 'admin']);
        Route::resource('/office', 'OfficeController', ['as' => 'admin']);
        Route::resource('/information', 'InformationController', ['as' => 'admin']);
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Office.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Office extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'address', 'phone', 'social', 'schedule', 'map',
    ];
}

app/Http/Controllers/Admin/OfficeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Office;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OfficeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.offices.index', [
            'offices' => Office::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.offices.create', [
            'office' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'address' => 'required|string|max:255',
        ]);

        Office::create([
            'name'      => $request['name'],
            'address'   => $request['address'],
            'phone'     => $request['phone'],
            'social'    => $request['social'],
            'schedule'  => $request['schedule'],
            'map'       => $request['map'],
        ]);

        return redirect()->route('admin.office.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Office  $office
     * @return \Illuminate\Http\Response
     */
    public function show(Office $office)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Office  $office
     * @return \Illuminate\Http\Response
     */
    public function edit(Office $office)
    {
        return view('admin.offices.edit', [
            'office' => $office
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Office  $office
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Office $office)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'address' => 'required|string|max:255',
        ]);

        $office->name = $request['name'];
        $office->address = $request['address'];
        $office->phone = $request['phone'];
        $office->social = $request['social'];
        $office->schedule = $request['schedule'];
        $office->map = $request['map'];
        $office->save();

        return redirect()->route('admin.office.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Office  $office
     * @return \Illuminate\Http\Response
     */
    public function destroy(Office $office)
    {
        $office->delete();
        return redirect()->route('admin.office.index');
    }
}

resources/views/admin/offices/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header">Добавление офиса</h2>

      <div class="card-body">
        {{-- форма для создания офиса --}}
        <form class="form-horizontal" action="{{route('admin.office.store')}}" method="post">
          {{ csrf_field() }}

          {{-- Подключение формы --}}
          @include('admin.offices.partials.form')
        </form>

      </div>
    </div>
  </div>

@endsection

resources/views/admin/offices/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header">Редактирование данных офиса</h2>

      <div class="card-body">
        {{-- форма для редактирования офиса --}}
        <form class="form-horizontal" action="{{route('admin.office.update', $office)}}" method="post">
          {{ method_field('put')}}
          {{ csrf_field() }}

          {{-- Подключение формы --}}
          @include('admin.offices.partials.form')
        </form>

      </div>
    </div>
  </div>

@endsection

resources/views/admin/offices/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header float-left">
        Список офисов
        <a href="{{route('admin.office.create')}}" class="btn btn-success float-right">
          Добавить офис
        </a>
      </h2>

        <div class="card-body">
          <table class="table table-responsiv table-striped table-bordered table-sm">
            <thead>
              <th scope="col">#</th>
              <th scope="col">Название</th>
              <th scope="col">Адрес</th>
              <th scope="col">Телефон</th>
              <th scope="col" class="text-right">Действия</th>
            </thead>
            <tbody>
              @forelse ($offices as $key => $office)
                <tr>
                  <th scope="row">{{++$key}}</th>
                  <td>{{$office->name}}</td>
                  <td>{{$office->address}}</td>
                  <td>{{$office->phone}}</td>
                  <td class="text-right">
                    <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('admin.office.destroy', $office)}}" method="post">
                      {{ method_field('delete') }}
                      {{ csrf_field() }}

                      <a class="btn btn-outline-primary btn-sm" href="{{route('admin.office.edit', $office)}}">Edit</a>

                      <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                    </form>
                  </td>
                </tr>
              @empty
                <tr>
                  <td colspan="5" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
              @endforelse
            </tbody>
            <tfoot>
              <tr>
                <td colspan="5">
                  <ul class="pagination pull-right">
                    {{$offices->links()}}
                  </ul>
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
  </div>

@endsection