routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::group(['middleware' => ['can:admin'] ], function () {
        Route::resource('/user', 'UserController', ['as' => 'admin']);
        Route::resource('/office', 'OfficeController', ['as' => 'admin']);
        Route::resource('/information', 'InformationController', ['as' => 'admin']);
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index', [
            'users' => User::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', [
            'user' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'role' => $request['role'],
            'password' => bcrypt($request['password'])
        ]);

        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id),
            ],
            'password' => 'nullable|string|min:6|confirmed',
        ]);

        $user->name = $request['name'];
        $user->email = $request['email'];
        $user->role = $request['role'];
        $request['password'] == null ?: $user->password = bcrypt($request['password']);
        $user->save();

        return redirect()->route('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.user.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header">Создание пользователя</h2>

      <div class="card-body">
        {{-- форма для создания пользователя --}}
        <form class="form-horizontal" action="{{route('admin.user.store')}}" method="post">
          {{ csrf_field() }}

          {{-- Подключение формы --}}
          @include('admin.users.partials.form')
        </form>

      </div>
    </div>
  </div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header">Редактирование пользователя</h2>

      <div class="card-body">
        {{-- форма для редактирования пользователя --}}
        <form class="form-horizontal" action="{{route('admin.user.update', $user)}}" method="post">
          {{ method_field('put')}}
          {{ csrf_field() }}

          {{-- Подключение формы --}}
          @include('admin.users.partials.form')
        </form>

      </div>
    </div>
  </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

        <h2 class="card-header float-left">
          Список пользователей
          <a href="{{route('admin.user.create')}}" class="btn btn-success float-right">
            Создать пользователя
          </a>
        </h2>

        <div class="card-body">
          <table class="table table-responsiv table-striped table-bordered table-sm">
            <thead>
              <th scope="col">#</th>
              <th scope="col">Имя</th>
              <th scope="col">Email</th>
              <th scope="col">Роль пользователя</th>
              <th scope="col" class="text-right">Действия</th>
            </thead>
            <tbody>
              @forelse ($users as $key => $user)
                <tr>
                  <th scope="row">{{++$key}}</th>
                  <td>{{$user->name}}</td>
                  <td>{{$user->email}}</td>
                  <td>{{$user->role}}</td>
                  <td class="text-right">
                    <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('admin.user.destroy', $user)}}" method="post">
                      {{ method_field('delete') }}
                      {{ csrf_field() }}

                      <a class="btn btn-outline-primary btn-sm" href="{{route('admin.user.edit', $user)}}">Edit</a>

                      <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                    </form>
                  </td>
                </tr>
              @empty
                <tr>
                  <td colspan="5" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
              @endforelse
            </tbody>
            <tfoot>
              <tr>
                <td colspan="5">
                  <ul class="pagination pull-right">
                    {{$users->links()}}
                  </ul>
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
  </div>

@endsection