routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::group(['middleware' => ['can:admin'] ], function () {
        Route::resource('/user', 'UserController', ['as' => 'admin']);
        Route::resource('/office', 'OfficeController', ['as' => 'admin']);
        Route::resource('/information', 'InformationController', ['as' => 'admin']);
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'number', 'status', 'master', 'notice', 'closed_at'
    ];

    /**
     * [scopeStatus description]
     * @param  \Illuminate\Database\Eloquent\Builder $query запрос
     * @param  string $status Статус заказа
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeStatus($query, $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Поиск по заказам для персонала
     */
    public function scopeSearchAdmin($query, $search)
    {
        return $query->where('number', 'like', '%'.$search.'%')
                  ->orWhere('master', 'like', '%'.$search.'%')
                  ->orWhere('notice', 'like', '%'.$search.'%');
    }
    /**
     * Поиск по заказам для пользователй
     */
    public function scopeSearchUser($query, $search)
    {
        return $query->where('number', 'like', $search);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Order;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->input('filter');
        $search = $request->input('search');
        if (isset($filter)) {
            $orders = Order::status($filter)->searchAdmin($search)->orderBy('created_at', 'desc')->paginate(10);
        } else {
            $orders = Order::searchAdmin($search)->orderBy('created_at', 'desc')->paginate(10);
        }
        return view('admin.orders.index', [
            'filter' => $filter,
            'orders' => $orders,
            'search' => $search,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $masters = User::where('role', 'master')->get();
        return view('admin.orders.create', [
            'order' => [],
            'masters' => $masters,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'number' => 'required|string|max:255|unique:orders',
            'master' => 'required',
        ]);

        Order::create($request->all());
        return redirect()->route('admin.order.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        if (Gate::denies('seller')) {
            $masters = User::where('role', 'master')->get();
            return view('admin.orders.edit', [
                'order' => $order,
                'masters' => $masters,
            ]);
        }
        return redirect()->route('admin.order.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        if (Gate::denies('seller')) {
            $validator = $request->validate([
                'number' => [
                    'required',
                    'string',
                    'max:255',
                    \Illuminate\Validation\Rule::unique('orders')->ignore($order->id)],
                'master' => 'required',
            ]);

            $order->number = $request['number'];
            $order->status = $request['status'];
            if ($order->status == 'Заказ закрыт') {
                $order->closed_at = now();
            }
            $order->master = $request['master'];
            $order->notice = $request['notice'];
            $order->save();
        }
        return redirect()->route('admin.order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        if (Gate::allows('admin')) {
            $order->delete();
        }
        return redirect()->route('admin.order.index');
    }
}

resources/views/admin/orders/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header">Добавление заказа</h2>

      <div class="card-body">
        {{-- форма для создания пользователя --}}
        <form class="form-horizontal" action="{{route('admin.order.store')}}" method="post">
          {{ csrf_field() }}

          {{-- Подключение формы --}}
          @include('admin.orders.partials.form')
        </form>

      </div>
    </div>
  </div>

@endsection

resources/views/admin/orders/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

      <h2 class="card-header">Редактирование заказа</h2>

      <div class="card-body">
        {{-- форма для редактирования пользователя --}}
        <form class="form-horizontal" action="{{route('admin.order.update', $order)}}" method="post">
          {{ method_field('put')}}
          {{ csrf_field() }}

          {{-- Подключение формы --}}
          @include('admin.orders.partials.form')
        </form>

      </div>
    </div>
  </div>

@endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    <div class="card">

        <h2 class="card-header float-left">
          Список заказов
          <a href="{{route('admin.order.create')}}" class="btn btn-success float-right">
            Добавить заказ
          </a>
        </h2>

        <div class="card-body">
            <form class="form-control-sm" action="{{route('admin.order.index')}}" method="get">
                <div class="form-row">
                    <div class="col">
                        <input class="form-control" type="search" name="search" placeholder="{{$search or "Поиск"}}" aria-label="Search">
                    </div>

                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Найти</button>
                </div>
            </form>
            <hr>
            <!-- Nav pills -->
            <ul class="nav nav-tabs nav-fill">
              <li class="nav-item">
                <a class="nav-link @if ($filter == '') active @endif" href="{{ route('admin.order.index') }}">Все заказы</a>
              </li>
              <li class="nav-item">
                <a class="nav-link @if ($filter == 'В ремонте') active @endif" href="{{ route('admin.order.index', ['filter'=>'В ремонте']) }}">В ремонте</a>
              </li>
              <li class="nav-item">
                <a class="nav-link @if ($filter == 'Требует согласования') active @endif" href="{{ route('admin.order.index', ['filter'=>'Требует согласования']) }}">Требует согласования</a>
              </li>
              <li class="nav-item">
                <a class="nav-link @if ($filter == 'Ремонт завершен') active @endif" href="{{ route('admin.order.index', ['filter'=>'Ремонт завершен']) }}">Ремонт завершен</a>
              </li>
              <li class="nav-item">
                <a class="nav-link @if ($filter == 'Заказ закрыт') active @endif" href="{{ route('admin.order.index', ['filter'=>'Заказ закрыт']) }}">Завершеные заказы</a>
              </li>
            </ul>
            <table class="table table-responsiv table-striped table-bordered table-sm">
              <thead>
                <th scope="col">Номер заказа</th>
                <th scope="col">Статус</th>
                <th scope="col">Мастер</th>
                <th scope="col" class="text-right">Действия</th>
              </thead>
              <tbody>
                @forelse ($orders as $key => $order)
                  <tr>
                    <td>{{$order->number}}</td>
                    <td>{{$order->status}}</td>
                    <td>{{$order->master}}</td>
                    <td class="text-right">

                    @can ('admin')
                      <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('admin.order.destroy', $order)}}" method="post">
                        {{ method_field('delete') }}
                        {{ csrf_field() }}
                    @endcan

                    @cannot ('seller')
                        <a class="btn btn-outline-primary btn-sm" href="{{route('admin.order.edit', $order)}}">Edit</a>
                    @endcan

                    @can ('admin')
                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                      </form>
                    @endcan
                    </td>
                  </tr>
                @empty
                  <tr>
                    <td colspan="5" class="text-center"><h2>Данные отсутствуют</h2></td>
                  </tr>
                @endforelse
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="5">
                    <ul class="pagination pull-right">
                        @if (isset($search))
                            {{$orders->appends(['search' => $search])->links()}}
                        @else
                            {{$orders->appends(['filter' => $filter])->links()}}
                        @endif

                    </ul>
                  </td>
                </tr>
              </tfoot>
            </table>

        </div>
      </div>
  </div>

@endsection